In [2]:
import numpy as np

In [43]:
A = np.random.rand(4, 6)

B = np.random.rand(6, 4)

C = np.zeros((4, 4))

for i in range(6):
   C += np.outer(A[:, i],  B[i, :])

print(C)

A@B


[[1.5969189  1.12895424 1.92351006 1.174624  ]
 [0.92127168 0.89056599 1.11975786 1.26672986]
 [1.93005073 2.25679002 2.23320795 2.0071676 ]
 [1.94237207 1.0110897  2.34057871 1.33724715]]


array([[1.5969189 , 1.12895424, 1.92351006, 1.174624  ],
       [0.92127168, 0.89056599, 1.11975786, 1.26672986],
       [1.93005073, 2.25679002, 2.23320795, 2.0071676 ],
       [1.94237207, 1.0110897 , 2.34057871, 1.33724715]])