In [1]:
import numpy as np

In [7]:
n = 4

A = 10*np.random.rand(n,n)

B = np.diag(np.diag(A))

print(A@A)

print(A*A)

print(B)

print(B@B)

print(B*B)


[[ 82.53390598  64.83505886  26.82301643 102.52244354]
 [ 75.32964482  36.05947821  37.47181205 101.70513761]
 [ 83.90204476  56.42329115  48.85396212  77.29628796]
 [134.43959187  64.61099611  57.09770464  96.04097845]]
[[3.48868138e+01 1.47973623e+00 1.39361649e+00 5.27137848e+01]
 [9.72590410e+01 4.28752010e-02 2.80165362e+01 3.17059772e-01]
 [5.56705305e+00 1.41532842e+01 2.07490045e+01 2.38720609e+01]
 [2.04902291e+01 5.32014265e+01 1.22450752e+00 5.36621479e+01]]
[[5.90650606 0.         0.         0.        ]
 [0.         0.20706328 0.         0.        ]
 [0.         0.         4.55510751 0.        ]
 [0.         0.         0.         7.32544524]]
[[3.48868138e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.28752010e-02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.07490045e+01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 5.36621479e+01]]
[[3.48868138e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.28