In [1]:
import numpy as np

In [18]:
A = 10*np.random.rand(4, 4)

B = 10*np.random.rand(4, 4)

S1 = A@A.T

S2 = B@B.T

print(S1+S2)

print(S1@S2) # not symmetric

print(S1*S2)


[[224.83671263 168.79553837 162.67896614 191.35884771]
 [168.79553837 258.18304194 250.90600481 230.32397441]
 [162.67896614 250.90600481 298.33377011 285.55238026]
 [191.35884771 230.32397441 285.55238026 333.38037321]]
[[31874.99681297 50667.62752507 56490.61488301 55796.64519522]
 [27294.09515896 43918.91741426 48550.2447615  47842.56630768]
 [30252.03256616 48489.81992611 54190.53550071 54453.55117403]
 [34053.6213141  54358.25645436 60871.26303535 61093.65463666]]
[[10750.94518575  6665.23399582  5368.74741039  9090.07022101]
 [ 6665.23399582 14029.25005101 12314.92669391 10909.50667352]
 [ 5368.74741039 12314.92669391 19032.05991922 17474.80147719]
 [ 9090.07022101 10909.50667352 17474.80147719 23619.27626494]]
