In [1]:
import numpy as np

In [26]:
A = np.random.rand(3,3)

M = np.zeros((3,3))

H = np.zeros((3,3))

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        detMatrix = np.delete(np.delete(A, i, 0), j, 1)
        M[i][j] = np.linalg.det(detMatrix)
        H[i][j] = 1**(i+j)

C = M*H

Ainverse = C.T*(1/np.linalg.det(A))

print(Ainverse)

print(np.linalg.inv(A))



[[-0.88129524 -1.65219038  0.54486155]
 [-0.80023978  0.83807099  0.7120247 ]
 [ 0.90073383  2.22849343  1.06358561]]
[[-0.88129524  1.65219038  0.54486155]
 [ 0.80023978  0.83807099 -0.7120247 ]
 [ 0.90073383 -2.22849343  1.06358561]]
