In [1]:
import numpy as np

In [2]:
A = np.random.rand(3, 3)

print(np.linalg.inv(A))

print(np.linalg.pinv(A))

[[-0.49407399  0.65443139  0.49851098]
 [ 1.03100548 -1.48168818  1.41300522]
 [ 0.29341195  1.4578594  -1.48591394]]
[[-0.49407399  0.65443139  0.49851098]
 [ 1.03100548 -1.48168818  1.41300522]
 [ 0.29341195  1.4578594  -1.48591394]]
