In [1]:
import numpy as np

In [8]:
A = np.random.rand(4, 4)
A = A@A.T
B = np.random.rand(4, 4)
B = B@B.T

eigenvals, eigenvecs = np.linalg.eig(A-B)
print(eigenvals)
print(eigenvecs) 
print(' ')
print(eigenvals**2) 
print(' ')
eigenvals, eigenvecs = np.linalg.eig(np.linalg.matrix_power(A, 2)-A@B-B@A+np.linalg.matrix_power(B, 2))
print(eigenvals)
print(eigenvecs) 


[-2.34303452 -0.00933667  0.49523954  2.09630274]
[[-0.69281044 -0.64329203 -0.32567655 -0.01112845]
 [-0.53000169  0.18053191  0.78038785 -0.27839046]
 [ 0.20214829 -0.11089293 -0.17830159 -0.95658108]
 [-0.44525045  0.73572166 -0.50312835 -0.08560107]]
 
[5.48981075e+00 8.71733371e-05 2.45262200e-01 4.39448519e+00]
 
[8.71733371e-05 2.45262200e-01 5.48981075e+00 4.39448519e+00]
[[-0.64329203  0.32567655  0.69281044 -0.01112845]
 [ 0.18053191 -0.78038785  0.53000169 -0.27839046]
 [-0.11089293  0.17830159 -0.20214829 -0.95658108]
 [ 0.73572166  0.50312835  0.44525045 -0.08560107]]
