In [1]:
import numpy as np

In [14]:
A = np.random.rand(4,4)

D = np.diag(np.diag(A))

print(D)

eigenval = np.linalg.eig(D)[0]

print(eigenval)

TL = np.tril(A)

eigenval = np.linalg.eig(TL)[0]

print(eigenval)

TU = np.triu(A)

eigenval = np.linalg.eig(TU)[0]

print(eigenval)

[[0.80993768 0.         0.         0.        ]
 [0.         0.45301911 0.         0.        ]
 [0.         0.         0.00231041 0.        ]
 [0.         0.         0.         0.49825383]]
[0.80993768 0.45301911 0.00231041 0.49825383]
[0.49825383 0.00231041 0.45301911 0.80993768]
[0.80993768 0.45301911 0.00231041 0.49825383]
