In [1]:
import numpy as np

In [2]:
A = np.random.rand(4,4)

Q,R = np.linalg.qr(A)

print(A.T@A)
print(R.T@R)

[[2.03012656 1.27730234 1.48198378 1.48677857]
 [1.27730234 1.34932629 1.10963315 1.27575862]
 [1.48198378 1.10963315 1.51659923 1.64158103]
 [1.48677857 1.27575862 1.64158103 1.90022295]]
[[2.03012656 1.27730234 1.48198378 1.48677857]
 [1.27730234 1.34932629 1.10963315 1.27575862]
 [1.48198378 1.10963315 1.51659923 1.64158103]
 [1.48677857 1.27575862 1.64158103 1.90022295]]
