In [1]:
import numpy as np

In [66]:
A = np.random.rand(5,3)

def pc(a, b):
   return (a.dot(b)/b.dot(b))*b

def gs(M):
    Q = np.zeros((M.shape))
    Q[:, 0] = M[:, 0]

    for i in range(1, M.shape[1]):
        Q[:, i] = M[:, i]
        for j in range(i):
            Q[:, i] -= pc(M[:, i], Q[:, j])

    for i in range(Q.shape[1]):
        Q[:, i] = Q[:, i]/np.linalg.norm(Q[:, i])

    return Q

Q = gs(A)

print(Q)

print(np.linalg.qr(A)[0])

[[ 0.39432346  0.02336904 -0.22779608]
 [ 0.26540886 -0.47501778  0.82079727]
 [ 0.00263574  0.51780639  0.41273136]
 [ 0.60588013  0.59716542  0.10723298]
 [ 0.63794158 -0.38611138 -0.30422804]]
[[-0.39432346  0.02336904  0.22779608]
 [-0.26540886 -0.47501778 -0.82079727]
 [-0.00263574  0.51780639 -0.41273136]
 [-0.60588013  0.59716542 -0.10723298]
 [-0.63794158 -0.38611138  0.30422804]]
