In [2]:
import numpy as np

In [11]:
A = np.random.rand(100, 100)

Q, R = np.linalg.qr(A)

Ainv = np.linalg.inv(R)@Q.T

print(np.round(Ainv-np.linalg.inv(A)))

[[-0. -0. -0. ...  0. -0.  0.]
 [ 0. -0. -0. ...  0. -0. -0.]
 [ 0.  0.  0. ... -0.  0.  0.]
 ...
 [-0.  0.  0. ... -0.  0.  0.]
 [-0.  0.  0. ...  0.  0.  0.]
 [-0.  0.  0. ...  0.  0.  0.]]
