In [1]:
import numpy as np

In [9]:
a = np.random.rand(5)
b = np.random.rand(5)

A = np.eye(5) - np.outer(a,b)

Ai = np.eye(5) + np.outer(a,b)/(1 - np.dot(a,b))

print(np.round(A@Ai))

[[ 1. -0.  0.  0.  0.]
 [ 0.  1. -0. -0.  0.]
 [-0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -0.]
 [-0.  0.  0.  0.  1.]]
