In [1]:
import numpy as np

In [7]:
M = np.random.rand(5,5)
N = np.random.rand(5,5)

s = np.random.randint(1, 2)

print(s*(M + N))

print(s*M + s*N)

[[0.62917254 1.32014916 1.28381927 1.191732   0.87215099]
 [0.4893265  1.20410849 0.47110243 0.57424269 1.0016876 ]
 [0.814608   0.82977056 1.23035151 0.64215767 1.19248333]
 [1.35892451 0.61791173 0.87891982 1.35378862 0.83981448]
 [0.74790318 0.76624996 1.07586418 0.53138737 0.41938594]]
[[0.62917254 1.32014916 1.28381927 1.191732   0.87215099]
 [0.4893265  1.20410849 0.47110243 0.57424269 1.0016876 ]
 [0.814608   0.82977056 1.23035151 0.64215767 1.19248333]
 [1.35892451 0.61791173 0.87891982 1.35378862 0.83981448]
 [0.74790318 0.76624996 1.07586418 0.53138737 0.41938594]]
