In [3]:
import numpy as np
from sympy import Matrix

In [16]:
def rref(M):
    return np.array(Matrix(M).rref()[0])

m = 5

n = 4

A = np.random.rand(4, 4)

B =  np.random.rand(5, 4)

C = np.random.rand(4, 5)

print(rref(A))

print(rref(B))

print(rref(C))

A[:,-2] = A[:,-1]

print(rref(A))



[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
[[1 0 0 0 -0.400794564960779]
 [0 1 0 0 -3.59297923261693]
 [0 0 1 0 5.08577251598124]
 [0 0 0 1 -0.522625758227887]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 1.00000000000000]
 [0 0 0 0]]
