In [2]:
import numpy as np

In [9]:
m = 3

A = np.random.rand(m, 6)

Us, Ss, Vs = np.linalg.svd(A)

L, V = np.linalg.eig(A.T@A)

U = np.zeros((m, m))

for i in range(m):
    U[:, i] = A@V[:, i]/np.sqrt(L[i])

print(Us)

U

[[ 0.69415078 -0.02758164 -0.71930101]
 [ 0.4140667  -0.80209212  0.4303452 ]
 [ 0.5888153   0.59656306  0.54535223]]


array([[-0.69415078, -0.02758164, -0.71930101],
       [-0.4140667 , -0.80209212,  0.4303452 ],
       [-0.5888153 ,  0.59656306,  0.54535223]])