In [1]:
import numpy as np

In [38]:
A = np.random.rand(4,4)

A = A@A.T

U, S, V = np.linalg.svd(A)

print(np.linalg.norm(U,2))
print(np.linalg.norm(V,2))
print(np.linalg.norm(U@V,2))

print(U@V)

0.9999999999999999
1.0
0.9999999999999999
[[ 1.00000000e+00 -4.99600361e-16  4.44089210e-16 -1.11022302e-16]
 [ 3.33066907e-16  1.00000000e+00 -2.22044605e-16 -1.38777878e-16]
 [-4.44089210e-16  2.77555756e-16  1.00000000e+00  1.66533454e-16]
 [ 1.11022302e-16  1.38777878e-16 -1.66533454e-16  1.00000000e+00]]
